language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install -g firebase-tools
after_success:  
  if [ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "true" ]; then
    - npm run build
    - firebase deploy --token $FIREBASE_TOKEN
  fi
