language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
install:
  - npm install 
before_script:
  - npm install -g firebase-tools
jobs:
  include:
    - stage: test
      script:
        - npm test
    - stage: deploy
      if: (branch = master) AND (type NOT IN (pull_request))
      script:
        - npm run build && firebase deploy --token $FIREBASE_TOKEN
      
