language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
branches:
  only:
    - master
before_script:
  - npm install -g firebase-tools
after_success:  
  - npm run build
  - firebase deploy --token $FIREBASE_TOKEN